# This is a basic workflow to help you get started with Actions

name: Build/Test/Deploy React Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths: ['**.*']
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Specify Node.JS Versions that the job will run on
    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set command using the runners shell to build and test the application
      - name: npm ci, build and test
        run: |
          npm i
          npm run build --if-present
          npm test

      - uses: peaceiris/actions-gh-pages@v4
        name: deploy to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
              

